#!/usr/bin/env bash

#brew
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

#zsh
brew install zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

#dotfiles
./install

#node
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.0/install.sh | bash
nvm install

# vim
rm -rf ~/.vim/bundle/Vundle.vim
git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim
vim +PluginInstall +qall 

# ruby
brew install rbenv
rbenv init

# python
brew install pyenv
pyenv install 2.7.15
pyenv global 2.7.15
git clone https://github.com/pyenv/pyenv-virtualenv.git $(pyenv root)/plugins/pyenv-virtualenv
brew install libtool libevent automake

# neovim
brew install neovim fzf the_silver_searcher
brew install --HEAD universal-ctags/universal-ctags/universal-ctags
