#!/usr/bin/env bash

mkdir -p ~/.config
ln -sf ~/dotfiles/.bash_profile ~/.bash_profile
ln -sf ~/dotfiles/.zshrc ~/.zshrc
ln -sf ~/dotfiles/.tern-config ~/.tern-config
ln -sf ~/dotfiles/.vim ~/.vim
ln -sf ~/dotfiles/.nvim ~/.config/nvim
ln -sf ~/dotfiles/.vimrc ~/.vimrc
ln -sf ~/dotfiles/.gvimrc ~/.gvimrc
ln -sf ~/dotfiles/.ctags ~/.ctags
ln -sf ~/dotfiles/.gitconfig ~/.gitconfig
ln -sf ~/dotfiles/.globalgitignore ~/.globalgitignore
